### ISSUE TITLE
Where to download the client

### ISSUE THREAD

**Issue by hui99995** [jakovmarkovanovic/clash-of-land#41]

**Comment by jakovmarkovanovic** [comment]
https://drive.google.com/file/d/11zeXomGXXnAkMp2brX8qHdAh6Gxpi16Z/view?usp=drivesdk

**Comment by hui99995** [comment]
谢谢 我把ip改成192.168.45.154成功进入了游戏

**Comment by jakovmarkovanovic** [comment]
then you have the same local ip as me

**Comment by hui99995** [comment]
I found IP through packet capturing, and then changed IP through virtual machine

**Comment by jakovmarkovanovic** [comment]
Ok

**Comment by hui99995** [comment]
Are you going to update 11. X next? I come from China, and people in our country like to play this game.

**Comment by jakovmarkovanovic** [comment]
for 11.x I'm not entirely sure, but I just know it's harder to update

**Comment by hui99995** [comment]
Can GL end play normally
